touch .gitignore
mkdir bin
touch   CHANGES.txt
mkdir   docs
touch   LICENSE.txt
touch    MANIFEST.in
touch    README.txt
touch   setup.py
mkdir    ctm_python_client
cd ctm_python_client
touch           __init__.py
touch          module1.py
touch          module2.py
cd ..
mkdir   test
cd test
touch             __init__.py
touch              test_module1.py
touch              test_module2.py